# Generated by Django 5.1.7 on 2025-04-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_profile_picture_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
