# Generated by Django 5.1.7 on 2025-04-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('coach', 'Coach'), ('athlete', 'Athlete')], default='athlete', max_length=10),
        ),
    ]
