# Generated by Django 5.1.7 on 2025-04-10 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'coach'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coached_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='individual_player',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'athlete'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'athlete'}, null=True, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
