# Generated by Django 5.1.7 on 2025-04-10 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_team_coach_alter_team_individual_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'athlete'}, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
